{% set xorg_name = "libpthread-stubs" %}
{% set xorg_category = "xcb" %}
{% set name = "pthread-stubs" %}
{% set version = "0.4" %}
{% set sha256 = "e4d05911a3165d3b18321cc067fdd2f023f06436e391c6a28dff618a78d2e733" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ xorg_name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

# NOTE: This package does not build or install any binary code on Windows.
# On Windows, bld.bat directly creates the pthread-stubs.pc pkg-config file
# without requiring a compiler or autotools.

build:
  number: 1003
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config                     # [unix]
    - gnuconfig                      # [unix]
    - make                           # [unix]
    - {{ compiler('c') }}            # [unix]
    - {{ stdlib("c") }}              # [unix]
  host:
    - xorg-util-macros               # [unix]

test:
  commands:

about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Stubs missing from libc for standard pthread functions"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw