travis:
  secure:
    BINSTAR_TOKEN: d3txNwKFPAdkU0BvBktGTihPncgt0Hq3JB/zlElW/zb9PoMpotCTh4k+CFLZmceJxpj69McxzdQWOjQfZ7Bk8hf5i/YxB+s12Tjc9vuW5VSYo5riPpDTDEugYGYNV5Fcz3r6m+haQEsOhg3IQBjb7OFUzWkqTBRlX2Dqp2j0+qFmqNS+3aTY5Fq2Ytp9A4bE1ZXkIBK96an4BC9wWkNY6CNfnkjnYhK5gYodftVK3BR80XMj62p33LiNkF+/9tAcHVF5We8g0TM+6shRGvZKlgvZ+v+g4G+UPyL5PM0/onr07EHLb8I6+MjUXBRj6Li2mcCGHD9Ne99ehfDRrUAj1LDzPXwHU1CVMuFXpbifQwR/QP/UyN8al/rYx0pf+JgIZPkskn9fFHvFKMnCu31dcPmpXcfJWb2AuwLvsfyDcxVm/Xbacc6HC668ip3GSo35qpNXAGZmIxnQatsL3e4DXPCb+kWYa6gmOeGvn+frdmGFopOk3PKAzhzS6mgjM/5S+EvT0MhMZvGe7XUq/3wEdlQgjx09BhaJVqR1/H3B0mqhdA/7RjuGYLF0l7YRltN8j6HOvHSuZ+5Os0Epsnf+kXgNSmK8PBYzBLaf1KbF7e+zRmTph34xH7X/sAAEAQPt4g3E4e5R891kKXU0mgKWn7KDSiqdZ+evHW4B/GFky5E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
