travis:
  secure:
    BINSTAR_TOKEN: cT7K+m4aHT58SMcEWO+9NULM9rWVxHHgjGyXqN6C+yd9y7ey8GcWXy066+vk0YmZH5cgrt3miMYXnfhuEqJdSZeT/ABiauOdZlq/M1cXHjKWGpHJ9tA119lYYgd+uqlcrj9w3dl4bc4/mVo6+25/od1QYNTnWNpBv+EIfwLGKlegULWXaCnZWUtluS47ozckwkhRy+2fUTMQhLQTWf5Y+RPD1rlysYfX8ZSqmKxnllZQs6CcBP+Bz0XQ1ExyQW1phI0iubgZzIVL/iF7yj4fyS0Tj+kVwSjehUgU7qO1XexXob6AZv7LcOJRVELuQTAZHIHkmVdzRk1ezlvXeyNMQRCbVKVpKd9npkoYLwskFO7hkDiYas1KMuS3vY2DbJtZmmJkftQhl0f2p5fMmfaQYrW2fGBzaqECaqO9XxhnAzh8ewO0pZiQy9EJD1RMDlhf38QFiq5+4jmw1ofH2DMVwqFxtpIuc9EVXg80d5xA/aLWTYITlGDMddTOJcK8YK2QBE7a43f/l5hMyH1sEPVaCDdRavonBpu0DlXIUZJ2iO9q7zyKjfJ/qM7q7ThSYy0ihlsnAsjNFlVItJWuZqzZdeRULGh1jzkPMPNugQSPfz1vf86DkiegB1/2RoWFk85HrAqSjdx222/UAHRpozi0mPMHHoXI7IciPXh+y9PQ8k8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
